version: '3.4'

services:
  db:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      - 'SA_PASSWORD=Pass12345'
      - 'ACCEPT_EULA=Y'
    ports:
      - 1433:1433
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"
